defmodule ArchLens.Town.Document do
  @moduledoc """
  Renders the `town_map` intermediate (`ArchLens.Town.combine/1`) to Markdown.

  Mirrors `ArchLens.Generator.Document`: the combiner already sorts every
  collection by a stable key, so this module adds no timestamp, git SHA, or
  absolute path and reproduces byte-identical Markdown for unchanged inputs. The
  JSON sidecar renders from the same map (via `ArchLens.Generator.Model.encode/1`),
  so the two committed town artifacts can never disagree.

  Every string it prints — app display names, `does` prose, endpoint fields,
  evidence — is carried verbatim from the input artifacts; nothing is synthesised.
  """

  @doc "Renders the town `map` to a Markdown string terminated by a single newline."
  @spec render(map()) :: String.t()
  def render(map) when is_map(map) do
    [
      header(),
      apps_section(map[:apps] || []),
      links_section(map[:links] || []),
      unresolved_section(map[:unresolved_externals] || [])
    ]
    |> Enum.intersperse([""])
    |> List.flatten()
    |> Enum.join("\n")
    |> ensure_trailing_newline()
  end

  defp header do
    [
      "# Town architecture",
      "",
      "_Generated by `mix arch_lens.town.map` — do not edit by hand._"
    ]
  end

  # --- apps --------------------------------------------------------------------

  defp apps_section([]), do: ["## Apps", "", "_No apps in the town manifest._"]

  defp apps_section(apps), do: ["## Apps", "" | Enum.map(apps, &app_bullet/1)]

  defp app_bullet(app) do
    "- **#{display_name(app)}** (`#{app.id}`, schema v#{app.source_schema_version})" <>
      " — #{counts_line(app.counts)}#{aliases_suffix(app.aliases)}"
  end

  defp display_name(app), do: app[:name] || app.id

  defp counts_line(counts) do
    [
      {"contexts", counts.contexts},
      {"actors", counts.actors},
      {"resources", counts.resources},
      {"oban_workers", counts.oban_workers},
      {"entry_points", counts.entry_points},
      {"external_systems", counts.external_systems}
    ]
    |> Enum.map_join(", ", fn {label, count} -> "#{label} #{count}" end)
  end

  defp aliases_suffix([]), do: ""
  defp aliases_suffix(aliases), do: " · aliases: #{Enum.map_join(aliases, ", ", &"`#{&1}`")}"

  # --- links -------------------------------------------------------------------

  defp links_section([]), do: ["## Cross-app links", "", "_No cross-app links resolved._"]

  defp links_section(links), do: ["## Cross-app links", "" | Enum.map(links, &link_bullet/1)]

  defp link_bullet(link) do
    "- **#{link.from}** → **#{link.to}** — `#{link.kind}` (#{link.basis})" <>
      "#{provenance_suffix(link.provenance)} · matched on `#{link.matched_on}`" <>
      "#{endpoint_suffix(link[:to_endpoint])}#{does_suffix(link[:does])}"
  end

  defp provenance_suffix([]), do: ""
  defp provenance_suffix(provenance), do: " · provenance: #{Enum.join(provenance, "+")}"

  defp endpoint_suffix(nil), do: ""

  defp endpoint_suffix(endpoint) do
    route = [endpoint[:method], endpoint[:path]] |> Enum.reject(&is_nil/1) |> Enum.join(" ")
    " · endpoint `#{route}`#{handler_part(endpoint)}"
  end

  defp handler_part(endpoint) do
    case {endpoint[:handler], endpoint[:kind]} do
      {nil, nil} -> ""
      {handler, nil} -> " → `#{handler}`"
      {nil, kind} -> " (#{kind})"
      {handler, kind} -> " → `#{handler}` (#{kind})"
    end
  end

  defp does_suffix(nil), do: ""
  defp does_suffix(does), do: " · _#{does}_"

  # --- unresolved externals ----------------------------------------------------

  defp unresolved_section([]) do
    ["## Unresolved externals", "", "_No unresolved externals._"]
  end

  defp unresolved_section(entries) do
    body =
      entries
      |> Enum.group_by(& &1.app)
      |> Enum.sort_by(fn {app, _entries} -> app end)
      |> Enum.flat_map(fn {app, group} -> app_group(app, group) end)

    ["## Unresolved externals", "" | body]
  end

  defp app_group(app, entries) do
    ["### #{app}", "" | Enum.map(entries, &unresolved_bullet/1)] ++ [""]
  end

  defp unresolved_bullet(entry) do
    "- `#{entry.external_id}`#{vendor_suffix(entry[:vendor])}#{evidence_suffix(entry[:evidence])}"
  end

  defp vendor_suffix(nil), do: ""
  defp vendor_suffix(vendor), do: " — #{vendor}"

  defp evidence_suffix(nil), do: ""

  defp evidence_suffix(evidence) do
    " (#{evidence |> Enum.map(&evidence_label/1) |> Enum.join(", ")})"
  end

  defp evidence_label(evidence) when is_map(evidence) do
    case {evidence["type"], evidence["value"]} do
      {nil, nil} -> ""
      {type, nil} -> to_string(type)
      {nil, value} -> to_string(value)
      {type, value} -> "#{type} #{value}"
    end
  end

  defp evidence_label(evidence), do: to_string(evidence)

  defp ensure_trailing_newline(string), do: String.trim_trailing(string, "\n") <> "\n"
end
