defmodule ArchLens.Town.DocumentTest do
  use ExUnit.Case, async: true

  alias ArchLens.Town.Document

  defp town_map(overrides) do
    Map.merge(
      %{
        schema_version: 1,
        kind: "town_map",
        apps: [],
        links: [],
        unresolved_externals: []
      },
      Map.new(overrides)
    )
  end

  test "renders the header and a single trailing newline" do
    markdown = Document.render(town_map([]))
    assert String.starts_with?(markdown, "# Town architecture\n")
    assert markdown =~ "_Generated by `mix arch_lens.town.map` — do not edit by hand._"
    assert String.ends_with?(markdown, "\n")
    refute String.ends_with?(markdown, "\n\n")
  end

  test "empty sections render honest empty states, not fabricated content" do
    markdown = Document.render(town_map([]))
    assert markdown =~ "_No apps in the town manifest._"
    assert markdown =~ "_No cross-app links resolved._"
    assert markdown =~ "_No unresolved externals._"
  end

  test "an app bullet prints its display name, id, schema, counts, and aliases" do
    app = %{
      id: "havi",
      name: "HAVI",
      aliases: ["havi", "havi.handgemacht.ai"],
      source_schema_version: 3,
      counts: %{
        contexts: 2,
        actors: 1,
        resources: 5,
        oban_workers: 0,
        entry_points: 3,
        external_systems: 2
      }
    }

    markdown = Document.render(town_map(apps: [app]))

    assert markdown =~
             "- **HAVI** (`havi`, schema v3) — contexts 2, actors 1, resources 5, " <>
               "oban_workers 0, entry_points 3, external_systems 2 · aliases: `havi`, `havi.handgemacht.ai`"
  end

  test "an app without a declared name falls back to its id and omits aliases" do
    app = %{
      id: "eval_lab",
      aliases: [],
      source_schema_version: 3,
      counts: %{
        contexts: 0,
        actors: 0,
        resources: 0,
        oban_workers: 0,
        entry_points: 0,
        external_systems: 1
      }
    }

    markdown = Document.render(town_map(apps: [app]))
    assert markdown =~ "- **eval_lab** (`eval_lab`, schema v3)"
    refute markdown =~ "aliases:"
  end

  test "a link bullet prints direction, transport, provenance, endpoint, and match" do
    link = %{
      id: "link:ccc=>havi:external:havi",
      from: "claude_code_course",
      to: "havi",
      kind: "http",
      basis: "collected_boundary",
      provenance: ["collected"],
      from_external_id: "external:havi",
      matched_on: "havi",
      to_endpoint: %{
        method: "GET",
        path: "/api/annotations",
        handler: "HaviWeb.AnnotationController",
        kind: "api"
      }
    }

    markdown = Document.render(town_map(links: [link]))

    assert markdown =~
             "- **claude_code_course** → **havi** — `http` (collected_boundary) · " <>
               "provenance: collected · matched on `havi` · endpoint `GET /api/annotations` → " <>
               "`HaviWeb.AnnotationController` (api)"
  end

  test "a link's verbatim does is rendered and an absent one adds nothing" do
    with_does = %{
      id: "link:a=>b:external:x",
      from: "a",
      to: "b",
      kind: "http",
      basis: "declared_external",
      provenance: ["declared"],
      from_external_id: "external:x",
      matched_on: "b",
      does: "Exports monthly billing reports."
    }

    without = Map.delete(with_does, :does)

    assert Document.render(town_map(links: [with_does])) =~ "· _Exports monthly billing reports._"
    refute Document.render(town_map(links: [without])) =~ "_Exports"
  end

  test "unresolved externals group by app with vendor and evidence" do
    entries = [
      %{
        app: "havi",
        external_id: "external:stripe",
        vendor: "Stripe",
        evidence: [%{"type" => "dep", "value" => "stripity_stripe"}]
      }
    ]

    markdown = Document.render(town_map(unresolved_externals: entries))
    assert markdown =~ "### havi"
    assert markdown =~ "- `external:stripe` — Stripe (dep stripity_stripe)"
  end

  test "render is byte-identical across re-runs" do
    map =
      town_map(
        apps: [
          %{
            id: "havi",
            name: "HAVI",
            aliases: ["havi"],
            source_schema_version: 3,
            counts: %{
              contexts: 1,
              actors: 0,
              resources: 0,
              oban_workers: 0,
              entry_points: 1,
              external_systems: 0
            }
          }
        ]
      )

    assert Document.render(map) == Document.render(map)
  end
end
