defmodule ArchLens.Generator.Document do
  @moduledoc """
  Renders the deterministic model map (`ArchLens.Generator.Model.to_map/1`) to
  Markdown.

  Determinism is the contract: the model already sorts every collection by a stable
  key and repo-relativises every call-site path, and this module adds no timestamp,
  git SHA, or absolute path. Two runs against unchanged code reproduce byte-identical
  Markdown, and — because the JSON sidecar renders from the same model map — the two
  artifacts can never disagree.
  """

  alias ArchLens.Collect.ModuleDoc

  alias ArchLens.Generator.Sections.{
    App,
    ContextDependencies,
    DataFlows,
    DataInventory,
    Decisions,
    DeclaredArchitecture,
    EntryPoints,
    ExternalSystems,
    RuntimeComponents
  }

  @doc "Renders the model `map` to a Markdown string terminated by a single newline."
  @spec render(map()) :: String.t()
  def render(model) when is_map(model) do
    ([
       header(),
       resources_section(model),
       edges_section(model),
       oban_section(model)
     ] ++ optional_sections(model))
    |> Enum.intersperse([""])
    |> List.flatten()
    |> Enum.join("\n")
    |> ensure_trailing_newline()
  end

  defp header do
    [
      "# Architecture",
      "",
      "_Generated by `mix arch_lens.gen.architecture` — do not edit by hand._"
    ]
  end

  defp resources_section(%{resources: []}) do
    ["## Resource privacy inventory", "", "_No Ash resources in scope._"]
  end

  defp resources_section(%{resources: resources}) do
    entries =
      resources
      |> Enum.map(&resource_entry/1)
      |> Enum.intersperse([""])
      |> List.flatten()

    ["## Resource privacy inventory", "" | entries]
  end

  defp resource_entry(resource) do
    [
      "### #{resource[:module]}",
      ""
      | doc_lines(resource[:doc]) ++
          posture_lines(resource[:privacy]) ++ provenance_lines(resource)
    ]
  end

  defp doc_lines(doc) when is_binary(doc), do: ["_#{ModuleDoc.first_sentence(doc)}_", ""]
  defp doc_lines(_doc), do: []

  defp posture_lines(%{posture: "declared", categories: categories} = privacy) do
    [
      "- Categories: `#{Enum.join(categories, ", ")}`",
      "- Legal basis: `#{inspect(privacy[:legal_basis])}`",
      retention_line(privacy[:retention])
    ]
  end

  defp posture_lines(%{posture: "declared"} = privacy) do
    [
      "- Data category: `#{inspect(privacy[:data_category])}`",
      "- Legal basis: `#{inspect(privacy[:legal_basis])}`",
      retention_line(privacy[:retention])
    ]
  end

  defp posture_lines(%{posture: "no_personal_data"}), do: ["- No personal data."]

  defp posture_lines(%{posture: "exempt"} = privacy) do
    ["- **Exempt from classification:** #{privacy[:reason]}"]
  end

  defp posture_lines(%{posture: "undeclared"}), do: ["- **Undeclared privacy posture.**"]

  defp retention_line(%{enforcement: "enforced", policy: policy} = retention) do
    "- Retention: `#{policy}` — enforced (#{enforcement_evidence(retention)})"
  end

  defp retention_line(%{enforcement: "declared_not_enforced", policy: policy}) do
    "- Retention: `#{policy}` — declared, not enforced"
  end

  defp retention_line(%{policy: policy}), do: "- Retention: `#{policy}`"

  defp enforcement_evidence(retention) do
    [
      retention[:field] && "field `#{retention[:field]}`",
      retention[:cleanup] && "cleanup `#{retention[:cleanup]}`"
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.join(", ")
  end

  defp provenance_lines(%{discovered_via_scan: true}) do
    ["- Discovered via module scan (no registered domain)."]
  end

  defp provenance_lines(_resource), do: []

  defp edges_section(%{edges: []}) do
    ["## Architectural edges", "", "_No architectural edges recorded._"]
  end

  defp edges_section(%{edges: edges}) do
    ["## Architectural edges", "" | Enum.map(edges, &edge_line/1)]
  end

  defp edge_line(edge) do
    "- `#{edge[:kind]}` `#{edge[:builder]}` → #{format_target(edge[:target])} (#{format_call_sites(edge[:call_sites])})"
  end

  defp format_target(nil), do: "_(none)_"
  defp format_target(target), do: "`#{target}`"

  defp format_call_sites(sites) do
    sites
    |> Enum.map(fn %{file: file, line: line} -> "#{file}:#{line}" end)
    |> Enum.join(", ")
  end

  defp oban_section(%{oban_workers: []}) do
    ["## Oban jobs", "", "_No Oban jobs registered._"]
  end

  defp oban_section(%{oban_workers: workers}) do
    ["## Oban jobs", "" | Enum.map(workers, &oban_line/1)]
  end

  defp oban_line(worker) do
    "- `#{worker[:module]}`#{queue_decoration(worker[:queue])}#{doc_suffix(worker[:doc])}"
  end

  defp queue_decoration(queue) when is_binary(queue), do: " [queue: #{queue}]"
  defp queue_decoration(_queue), do: ""

  defp doc_suffix(doc) when is_binary(doc), do: " — #{ModuleDoc.first_sentence(doc)}"
  defp doc_suffix(_doc), do: ""

  # Optional sections in a fixed, deterministic order; each renders `[]` (and is
  # dropped) when its field is empty.
  defp optional_sections(model) do
    [
      EntryPoints.render(model[:entry_points]),
      RuntimeComponents.render(model[:runtime_components]),
      ExternalSystems.render(model[:external_systems]),
      ContextDependencies.render(model[:context_dependencies]),
      DataFlows.render(model[:flows]),
      DataInventory.render(model[:data_inventory]),
      DeclaredArchitecture.render(model[:declared_architecture]),
      Decisions.render(model[:decisions]),
      App.render(model[:app])
    ]
    |> Enum.reject(&(&1 == []))
  end

  defp ensure_trailing_newline(string) do
    String.trim_trailing(string, "\n") <> "\n"
  end
end
