defmodule ArchLens.Generator.Document do
  @moduledoc """
  Renders a resolved `ArchLens.Generator.Scope` to deterministic Markdown.

  Determinism is the contract: every collection is already sorted by a stable key
  in the scope, and this module adds no timestamp, git SHA, or absolute
  filesystem path. Any path that reaches the output (an edge call-site file) is
  made repo-relative first. Two runs against unchanged code therefore reproduce
  byte-identical Markdown.
  """

  alias ArchLens.Edge
  alias ArchLens.Generator.{Retention, Scope}
  alias ArchLens.Privacy.{Declaration, Info}

  @doc "Renders `scope` to a Markdown string terminated by a single newline."
  @spec render(Scope.t()) :: String.t()
  def render(%Scope{} = scope) do
    [
      header(),
      resources_section(scope),
      edges_section(scope),
      oban_section(scope)
    ]
    |> Enum.intersperse([""])
    |> List.flatten()
    |> Enum.join("\n")
    |> ensure_trailing_newline()
  end

  defp header do
    [
      "# Architecture",
      "",
      "_Generated by `mix arch_lens.gen.architecture` — do not edit by hand._"
    ]
  end

  defp resources_section(%Scope{resources: []}) do
    ["## Resource privacy inventory", "", "_No Ash resources in scope._"]
  end

  defp resources_section(%Scope{} = scope) do
    entries =
      scope.resources
      |> Enum.map(&resource_entry(&1, scope))
      |> Enum.intersperse([""])
      |> List.flatten()

    ["## Resource privacy inventory", "" | entries]
  end

  defp resource_entry(resource, %Scope{} = scope) do
    [
      "### #{module_name(resource)}",
      "" | posture_lines(resource, scope) ++ provenance_lines(resource, scope)
    ]
  end

  defp posture_lines(resource, %Scope{} = scope) do
    case Info.posture(resource) do
      %Declaration{} = declaration ->
        [
          "- Data category: `#{inspect(declaration.data_category)}`",
          "- Legal basis: `#{inspect(declaration.legal_basis)}`",
          retention_line(resource, declaration, scope)
        ]

      :no_personal_data ->
        ["- No personal data."]

      :undeclared ->
        # Unreachable in practice: the completeness gate fails generation before
        # rendering when any resource is undeclared. Rendered defensively.
        ["- **Undeclared privacy posture.**"]
    end
  end

  defp retention_line(resource, %Declaration{retention: retention}, %Scope{edges: edges}) do
    case Retention.classify(resource, edges) do
      {:enforced, evidence} ->
        "- Retention: `#{retention}` — enforced (#{enforcement_evidence(evidence)})"

      {:declared_not_enforced, _evidence} ->
        "- Retention: `#{retention}` — declared, not enforced"

      {:none, _} ->
        "- Retention: `#{retention}`"
    end
  end

  defp enforcement_evidence(evidence) do
    [
      evidence[:field] && "field `#{evidence[:field]}`",
      evidence[:cleanup] && "cleanup `#{module_name(evidence[:cleanup])}`"
    ]
    |> Enum.reject(&is_nil/1)
    |> Enum.join(", ")
  end

  defp provenance_lines(resource, %Scope{domain_resources: domain_resources}) do
    if resource in domain_resources do
      []
    else
      ["- Discovered via module scan (no registered domain)."]
    end
  end

  defp edges_section(%Scope{edges: []}) do
    ["## Architectural edges", "", "_No architectural edges recorded._"]
  end

  defp edges_section(%Scope{edges: edges}) do
    rows =
      edges
      |> Enum.sort_by(&edge_sort_key/1)
      |> Enum.map(&edge_line/1)

    ["## Architectural edges", "" | rows]
  end

  defp edge_line(%Edge{} = edge) do
    "- `#{edge.kind}` `#{module_name(edge.builder)}` → #{format_target(edge.target)} (#{format_call_site(edge.call_site)})"
  end

  defp edge_sort_key(%Edge{} = edge) do
    {inspect(edge.builder), inspect(edge.call_site), Atom.to_string(edge.kind)}
  end

  defp oban_section(%Scope{oban_workers: []}) do
    ["## Oban jobs", "", "_No Oban jobs registered._"]
  end

  defp oban_section(%Scope{oban_workers: workers}) do
    rows = Enum.map(workers, &"- `#{module_name(&1)}`")
    ["## Oban jobs", "" | rows]
  end

  defp format_target(target) when is_binary(target), do: "`#{target}`"

  defp format_target(target) when is_atom(target) and not is_nil(target),
    do: "`#{module_name(target)}`"

  defp format_target(nil), do: "_(none)_"
  defp format_target(target), do: "`#{inspect(target)}`"

  defp format_call_site({module, file, line})
       when is_atom(module) and is_binary(file) and is_integer(line) do
    "at `#{relativize(file)}:#{line}`"
  end

  defp format_call_site({module, function, arity})
       when is_atom(module) and is_atom(function) and is_integer(arity) do
    "at `#{module_name(module)}.#{function}/#{arity}`"
  end

  defp format_call_site(other), do: "at `#{inspect(other)}`"

  # Repo-relative-ise a path so no absolute filesystem path ever reaches the
  # rendered document. Falls back to the basename if the path is not under the
  # project root.
  defp relativize(path) do
    relative = Path.relative_to(path, File.cwd!())

    case Path.type(relative) do
      :absolute -> Path.basename(relative)
      _ -> relative
    end
  end

  defp module_name(module) when is_atom(module) do
    case Atom.to_string(module) do
      "Elixir." <> rest -> rest
      other -> other
    end
  end

  defp module_name(other), do: inspect(other)

  defp ensure_trailing_newline(string) do
    String.trim_trailing(string, "\n") <> "\n"
  end
end
